version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: covelent-server
    env_file:
      - /home/ec2-user/configs/covelent.env
    depends_on:
      - redis
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - /home/ec2-user/configs/covelnt.json:/usr/src/app/configs/covelnt.json
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    container_name: covelent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: